module Insight;

private fun jserialise<T>(x: T): JSON.String {
  ret = "";
  capture = (s) -> !ret = s;
  writer = mutable Debug.BufferedWriter(capture, Int::max);
  inspect(x).print(writer);
  writer.flush();
  JSON.String(ret);
}

private fun jserialiseStr(x: String): JSON.String {
  JSON.String(x)
}

private fun jserialiseInt(x: Int): JSON.Number {
  JSON.IntNumber(x)
}

private fun jserialiseFloat(x: Float): JSON.Number {
  JSON.FloatNumber(x)
}

private fun jserialiseKey(key: SKStore.Key): JSON.Value {
  key match {
  | k @ SKDB.RowKey _ -> jserialiseFile(k.row)
  | k @ _ -> jserialise(k)
  }
}

private fun jserialiseFile(file: SKStore.File): JSON.Value {
  file match {
  | SKDB.RowValues(values, _repeat) ->
    JSON.Array::createFromIterator(
      values.iterator().map(v ->
        v match {
        | None() -> JSON.Null()
        | Some(SKDB.CInt(x)) -> jserialiseInt(x)
        | Some(SKDB.CFloat(x)) -> jserialiseFloat(x)
        | Some(SKDB.CString(s)) -> jserialiseStr(s)
        | Some(SKDB.CJSON(_)) -> invariant_violation("TODO: map to JSON")
        | Some(SKDB.CType _) -> invariant_violation("TODO: map to something")
        }
      ),
    )
  | _ -> jserialise(file)
  }
}

private fun buildDepObject(
  context: mutable SKStore.Context,
  dirname: SKStore.DirName,
  key: SKStore.Key,
): JSON.Object {
  obj = mutable Map<String, JSON.Value>[];
  obj!["dir"] = JSON.String(dirname.dirName);
  obj!["key"] = jserialiseKey(key);

  dir = context.dirs.maybeGet(dirname) match {
  | None() -> invariant_violation(`could not find ${dirname}`)
  | Some(dir @ SKStore.EagerDir _) -> dir
  | Some(_) -> invariant_violation("unsupported dir type")
  };

  obj!["dir_is_input"] = JSON.Bool(dir.input);

  data = dir.unsafeGetAllDataIter(key); // iterator is empty if key does not exist

  contributions = mutable Vector[];

  for ((tick, source, writer, files) in data) {
    contribution = mutable Map<String, JSON.Value>[];

    contribution!["tick"] = jserialiseInt(tick.value);
    contribution!["writer"] = jserialise(writer);

    contribution!["files"] = JSON.Array::createFromIterator(
      files.iterator().map(jserialiseFile),
    );

    contribution!["mapfns"] = JSON.Array::createFromIterator(
      dir.parents.maybeGet(source.dirName) match {
      | None() -> Array[].iterator()
      | Some(fns) ->
        fns
          .iterator()
          .filter(f ->
            f match {
            | (_, None(), _) -> true
            | (
              _,
              Some(ranges),
              _,
            ) if (
              ranges.any(range -> range.start <= key && key <= range.end)
            ) ->
              true
            | _ -> false
            }
          )
          .map(f -> {
            (mapfn, _, _) = f;
            mapfn
          })
          .map(jserialise)
      },
    );

    if (!dir.input) {
      contribution!["source"] = buildDepObject(
        context,
        source.dirName,
        source.baseName,
      );
    };

    contributions.push(JSON.Object(contribution.chill()));
  };

  obj!["contributions"] = JSON.Array(contributions.chill());
  JSON.Object(obj.chill());
}

fun upstream(
  context: mutable SKStore.Context,
  dirname: SKStore.DirName,
  key: SKStore.Key,
): void {
  // TODO: parents for the functions that were used at each step
  // TODO: deps from context

  obj = buildDepObject(context, dirname, key);
  print_string(obj.encode());
}

module end;

// TODO:
// listing all the keys
// for (k in dir.keys()) {
//   print_debug_raw(": [mjxna] key: ");
//   debug(k);
// };
